services:
  db:
    image: postgres
    container_name: db
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - "6000:5432"
  # pgagent:
  #   image: chiavegatto/postgres-pgagent
  #   container_name: pgagent
  #   entrypoint: /bin/sh -c
  #               "/tmp/wait-for-it.sh postgres:5432 --timeout=120 &&
  #               PGPASSWORD='postgres' psql -U postgres -h postgres -p 5432 -d test -c 'CREATE EXTENSION IF NOT EXISTS pgagent;' &&
  #               PGPASSWORD='postgres' pgagent -f hostaddr=postgres dbname=postgres user=postgres port=5432"
    # environment:
    #   - TIMEZONE=America/Manaus
  yahoo-api:
    build: ./yahoo-api/
    container_name: yahoo-api
  dashboard:
    build: ./dashboard/
    container_name: dashboard
    ports:
      - "8501:8501"